version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
  hugo: circleci/hugo@1.2.2
jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site
      - aws-cli/setup
      - run: aws s3 rm s3://d.ai.sy/public/ --recursive
      - run: aws s3 cp my-site/public/ s3://d.ai.sy/ --recursive

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: quickstart/
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build
